### PR TITLE
Fix #1683 allow OAuth2 authorizationUrl with user provided query parameters

### LINKED ISSUE #1683: Oauth2: auth url with required pre-exisiting parameters
My oauth2 app requires that authorization url contains a few required parameters that are out of oauth2 specification. When trying to create a request in Bruno, I hit the wall where the actual authorization url is compiled incorrectly:

My Auth URL looks like this:
```
{{keycloak_url}}/realms/{{realm}}/protocol/openid-connect/auth?login_hint={{user_email}}
```
Bruno appends 
```
?client_id=MYID&redirect_uri=MYURL&response_type=code&scope=openid
```
while I'd expected it appended 
```
&client_id=MYID&redirect_uri=MYURL&response_type=code&scope=openid
```

Bruno: 1.10.0
#1003

### PR DESCRIPTION
**Pull request by pietrygamat**
# Description

In some cases the authroization url may already contain some query parameters expected by the specific applicaiton, in which case oauth2 authorization request specific parameters should be appended to the list. Previous implementation assumed no query component in the authrization URI.

Fixes #1683 

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

### CODE REVIEW

File: packages/bruno-electron/src/ipc/network/oauth2-authorization-code-helper.js [hunk 1]
```diff
@@ -25,7 +25,10 @@ const getOAuth2AuthorizationCode = (request) => {
   return new Promise(async (resolve, reject) => {
     const { oauth2 } = request;
     const { callbackUrl, clientId, authorizationUrl, scope } = oauth2;
-    const authorizationUrlWithQueryParams = `${authorizationUrl}?client_id=${clientId}&redirect_uri=${callbackUrl}&response_type=code&scope=${scope}`;
+    const authorizationUrlWithQueryParams =
+      `${authorizationUrl}` +
+      (authorizationUrl.indexOf('?') > -1 ? '&' : '?') +
+      `client_id=${clientId}&redirect_uri=${callbackUrl}&response_type=code&scope=${scope}`;
```
Comment (pietrygamat) [inline packages/bruno-electron/src/ipc/network/oauth2-authorization-code-helper.js]: Feedback on the most idiomatic syntax for this apprieciated.

**Comment by helloanoop** [comment]
@pietrygamat The syntax looks good. Can you resolve the conflicts?

**Comment by helloanoop** [comment]
Thanks for taking care of this @pietrygamat !

cc @lohxt1
