### PR TITLE
bugfix(#2431) Refactor URL construction in Postman collection processing

### LINKED ISSUE #2431: Postman import silently drops url values
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When importing postman collection the url path of every request gets dropped and becomes empty.

How to reproduce:
* download official Atlassian postman collection export for Jira Cloud API https://developer.atlassian.com/cloud/jira/platform/jiracloud.3.postman.json
* Open bruno and import postman collection from downloaded file
* Observe all requests have no URL value

### .bru file to reproduce the bug

meta {
  name: Get all projects
  type: http
  seq: 1
}

get {
  url: 
  body: none
  auth: basic
}

query {
  ~expand: {{expand}}
  ~recent: {{recent}}
  ~properties: {{properties}}
}

headers {
  Accept: application/json
}

auth:basic {
  username: {{username}}
  password: {{apiToken}}
}

### Screenshots/Live demo link

image

### LINKED ISSUE #3113: Importing a postman collection for commercetools fails
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When importing the postman collection from commercetools (https://github.com/commercetools/commercetools-postman-collection/blob/master/api/collection.json), I only get the message "Import collection failed". It doesn't matter if I uncheck the "Auto translate postman scripts".

I'm using Bruno v1.28.0. 

### .bru file to reproduce the bug

_No response_

### Screenshots/Live demo link

image

### PR DESCRIPTION
**Pull request by sanjai0py**
# Description

Fixes #2431

> The PR improves the handling of URL construction when processing Postman collections. Previously, the code was not handling the case where the request.url field was an object without a raw field. The new code now correctly constructs the URL from the components of the request.url object when necessary.

Fixes #3113

> Now the request method is converted to uppercase during import.

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [ ] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

### CODE REVIEW

File: packages/bruno-app/src/utils/importers/postman-collection.js [hunk 1]
```diff
@@ -54,6 +54,23 @@ const convertV21Auth = (array) => {
...
+  } else {
+    const { protocol, host, path, port, query } = url;
+    const hostStr = Array.isArray(host) ? host.join('.') : host;
+    const pathStr = Array.isArray(path) ? path.join('/') : path;
+    const portStr = port ? `:${port}` : '';
+    const queryStr = query && query.length > 0 ? `?${query.map((q) => `${q.key}=${q.value}`).join('&')}` : '';
+    urlStr = `${protocol}://${hostStr}${portStr}/${pathStr}${queryStr}`;
+  }
+  return urlStr;
+};
```
Comment (pietrygamat) [inline packages/bruno-app/src/utils/importers/postman-collection.js]: Check this case please, this is losing hash section of url:
```
"item": [
		{
			"name": "Request",
			"request": {
				"method": "GET",
				"header": [],
				"url": {
					"raw": "https://localhost/param1/param2?param3&param4=b&param5=(size=small;color=red)#this-is-framgment",
					"protocol": "https",
					"host": [
						"localhost"
					],
					"path": [
						"param1",
						"param2"
					],
					"query": [
						{
							"key": "param3",
							"value": null
						},
						{
							"key": "param4",
							"value": "b"
						},
						{
							"key": "param5",
							"value": "(size=small;color=red)"
						}
					],
					"hash": "this-is-framgment"
				}
			},
			"response": []
		}
	]
```

Comment (sanjai0py) [reply packages/bruno-app/src/utils/importers/postman-collection.js]: Thank you for the review. I believe we should not include the hash values in the URL. As per Wikipedia, 

> "The fragment identifier functions differently to the rest of the URI: its processing is exclusively client-sided with no participation from the web server" \
— <cite>[Wikipedia](https://www.wikiwand.com/en/articles/Fragment_identifier)<cite>

**Review by anusreesubash — APPROVED** [review]
