### PR TITLE
fix: support multiline example names

### LINKED ISSUE #6873: Cannot save request from imported collection after modifying it
### I have checked the following:

- [x] I have searched existing issues and found nothing related to my issue.

### This bug is:

- [x] making Bruno unusable for me
- [x] slowing me down but I'm able to continue working
- [x] annoying
- [x] this feature was working in a previous version but is broken in the current release.

### Bruno version

3.0.2

### Operating System

MacOS 15.7.3

### Describe the bug

I'm unable to save the request after a change. I've imported the collection from a postman file.

Steps to reproduce: 

1. Download a Zoom API Postman collection https://www.postman.com/zoom-developer
2. Import it into Bruno 
3. Modify any request and save it
4. You will see `name is required` error toast 

### .bru file to reproduce the bug

You don't need this, just download any Zoom collection from their page and import it into Bruno (in my case was the Meetings)

[bruno.json](https://github.com/user-attachments/files/24764883/bruno.json)

collection.bru :

Image

### Screenshots/Live demo link

Check video :

https://github.com/user-attachments/assets/4ad6480d-02ab-4797-8ca8-19e066fd18fc

### PR DESCRIPTION
**Pull request by gopu-bruno**
### Description

Previously, example names with multiline content would fail to parse, resulting in a "name is required" validation error when saving requests imported from Postman collections.

Fixes #6873

### Changes
- Added support for multiline example names 

#### Contribution Checklist:

- [ ] **I've used AI significantly to create this pull request**
- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [ ] **I have added screenshots or gifs to help explain the change if applicable.**
- [ ] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [ ] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

#### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

## Summary by CodeRabbit

* **Bug Fixes**
  * Response example names are now normalized: multiline/newline characters are converted to single-line spacing, leading/trailing whitespace is trimmed, and empty names fall back to sensible defaults (e.g., "Example N" or "<status> Response").

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: packages/bruno-lang/v2/src/example/bruToJson.js [hunk 1]
```diff
@@ -53,7 +53,9 @@ const exampleGrammar = ohm.grammar(`Example {
   textchar = ~nl any
 
   // Root level properties
-  name =  "name" st* ":" st* valuechar* st*
+  name =  "name" st* ":" st* namevalue st*
+  namevalue = multilinenamevalue | singlelinevalue
+  multilinenamevalue = (~(nl* ("request" | "response" | "description") st* ":") any)+
```
Comment (sanish-bruno) [inline packages/bruno-lang/v2/src/example/bruToJson.js]: @gopu-bruno i think this logic of negating request, response, description might not be the right way to approach this. may be we don't even have to make any changes within the bru grammar.

The problem seems to that, when we create bru files we are writing the CRLF too, it doesn't seems to get parsed back properly, as \r\n are present in the string, may be we can pre-process the name to replace any `\n` or `\r\n` with space as it is unlikely that a name will need a new line

the description will need to support multiline `'''`

File: packages/bruno-lang/v2/src/example/bruToJson.js [hunk 2]
```diff
@@ -80,9 +82,15 @@ const astExampleAttribute = {
   // Root level properties
   name(_1, _2, _3, _4, value, _6) {
     return {
-      name: value.sourceString ? value.sourceString.trim() : ''
+      name: value.ast ? value.ast.trim() : ''
     };
   },
+  namevalue(content) {
```
Comment (sanish-bruno) [inline packages/bruno-lang/v2/src/example/bruToJson.js]: @gopu-bruno please add test cases to verify various scenarios that may happen.

File: packages/bruno-lang/v2/src/example/bruToJson.js (hunk 1 above)
Comment (sanish-bruno) [inline packages/bruno-lang/v2/src/example/bruToJson.js]: @gopu-bruno what will happen if the name itself contains 'request' , 'response', 'description' string? for examples `delete \n request` `get \n description`

File: packages/bruno-lang/v2/src/example/bruToJson.js [hunk 3]
```diff
@@ -80,9 +82,15 @@ const astExampleAttribute = {
...
+    return content.ast;
+  },
+  multilinenamevalue(chars) {
+    return chars.sourceString ? chars.sourceString.replace(/\r\n/g, '\n').trim() : '';
```
Comment (sanish-bruno) [inline packages/bruno-lang/v2/src/example/bruToJson.js]: @gopu-bruno i think we may need to replace them with a space, rather than `\n` we shouldn't have allowed `\n` within the name in the first place

File: packages/bruno-lang/v2/src/example/bruToJson.js (hunk 1 above)
Comment (gopu-bruno) [reply packages/bruno-lang/v2/src/example/bruToJson.js]: Just having the strings 'request', 'response', or 'description' in the name wouldn't cause any issues, as we're checking for actual field markers ( `request:`, `response:`, `description:`)


image
image

File: packages/bruno-lang/v2/src/example/bruToJson.js (hunk 2 above)
Comment (gopu-bruno) [reply packages/bruno-lang/v2/src/example/bruToJson.js]: @sanish-bruno, added test case covering various scenarios.

File: packages/bruno-lang/v2/src/example/bruToJson.js (hunk 3 above)
Comment (gopu-bruno) [reply packages/bruno-lang/v2/src/example/bruToJson.js]: Updated the code to replace newline (\n and \r\n) with spaces.

**Review by bijin-bruno — APPROVED** [review]
