### PR TITLE
fix(#2122): add specific error status codes

### LINKED ISSUE #2122: cli does not yield specific exit codes for different problems
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When using the cli in build pipelines, it's helpful to be able to identify the different reasons why an invocation failed:

- assertion failed
- non-existing output dir
- environment not found
- invalid output format
- ...

By providing specific, immutable exit codes for all these scenarios, the pipeline/engineer can react appropriately without having to debug the error.

I propose to yield different exit codes for different problems via `process.exit(...)`.

### .bru file to reproduce the bug

_No response_

### Screenshots/Live demo link

Running a collection with a failing assertion yields an exit code `1`:

```
$ bru run
...
$ echo $?
1
```

Running a collection with a non-existing environment prints an error message, but exits with `0` (successful):

```
$ bru run --env foo
Environment file not found: environments/foo.bru
...
$ echo $?
0
```

### PR DESCRIPTION
**Pull request by jzorn**
# Description

This change adds specific exit status codes to identify different problems programatically, fixes #2122

### Contribution Checklist:

- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [x] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [x] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

### CODE REVIEW

**Comment by jzorn** [comment]
Hey, is there anything I can do to improve this PR to get it merged? :)

File: packages/bruno-cli/src/constants.js [hunk 1]
```diff
@@ -3,7 +3,48 @@ const { version } = require('../package.json');
...
+const EXIT_STATUS_ERROR_MALFORMED_ENV_OVERRIDE = 7;
+
+// Environment overrides format incorrect
+const EXIT_STATUS_ERROR_INCORRECT_ENV_OVERRIDE = 8;
+
+// Invalid output format requested
+const EXIT_STATUS_ERROR_INCORRECT_OUTPUT_FORMAT = 9;
+
+// Everything else
+const EXIT_STATUS_ERROR_GENERIC = 255;
```
Comment (andreassiegel) [inline packages/bruno-cli/src/constants.js]: I like the idea of having different result codes to allow for more fine-grained error handling in scripting.

With respect to further extensibility, I'd suggest to define the error codes as different attributes of an object so that a single export is sufficient:
```suggestion
// Exit codes
const EXIT_STATUS = {
  // One or more assertions, tests, or requests failed
  ERROR_FAILED_COLLECTION: 1,
  // The specified output dir does not exist
  ERROR_MISSING_OUTPUT_DIR: 2,
  // request chain caused an endless loop
  ERROR_INFINTE_LOOP: 3,
  // bru was called outside of a collection root
  ERROR_NOT_IN_COLLECTION: 4,
  // The specified file was not found
  ERROR_FILE_NOT_FOUND: 5,
  // The specified environment was not found
  ERROR_ENV_NOT_FOUND: 6,
  // Environment override not presented as string or object
  ERROR_MALFORMED_ENV_OVERRIDE: 7,
  // Environment overrides format incorrect
  ERROR_INCORRECT_ENV_OVERRIDE: 8,
  // Invalid output format requested
  ERROR_INCORRECT_OUTPUT_FORMAT: 9,
  // Everything else
  ERROR_GENERIC: 255,
};
```

File: packages/bruno-cli/src/constants.js [hunk 2]
```diff
@@ -3,7 +3,48 @@ const { version } = require('../package.json');
...
+  EXIT_STATUS_ERROR_FAILED_COLLECTION,
+  EXIT_STATUS_ERROR_MISSING_OUTPUT_DIR,
+  EXIT_STATUS_ERROR_INFINTE_LOOP,
+  EXIT_STATUS_ERROR_NOT_IN_COLLECTION,
+  EXIT_STATUS_ERROR_FILE_NOT_FOUND,
+  EXIT_STATUS_ERROR_ENV_NOT_FOUND,
+  EXIT_STATUS_ERROR_MALFORMED_ENV_OVERRIDE,
+  EXIT_STATUS_ERROR_INCORRECT_ENV_OVERRIDE,
+  EXIT_STATUS_ERROR_INCORRECT_OUTPUT_FORMAT,
+  EXIT_STATUS_ERROR_GENERIC
```
Comment (andreassiegel) [inline packages/bruno-cli/src/constants.js]: With the other suggested change, this export would be sufficient, and new error codes can be added without having to modify the module export further:

```suggestion
  EXIT_STATUS
```

File: packages/bruno-cli/src/commands/run.js [hunk 3]
```diff
@@ -255,7 +256,7 @@ const handler = async function (argv) {
     const brunoJsonExists = await exists(brunoJsonPath);
     if (!brunoJsonExists) {
       console.error(chalk.red(`You can run only at the root of a collection`));
-      return;
+      process.exit(constants.EXIT_STATUS_ERROR_NOT_IN_COLLECTION);
```
Comment (andreassiegel) [inline packages/bruno-cli/src/commands/run.js]:
```suggestion
      process.exit(constants.EXIT_STATUS.ERROR_NOT_IN_COLLECTION);
```

File: packages/bruno-cli/src/commands/run.js [hunk 4]
```diff
@@ -266,7 +267,7 @@ const handler = async function (argv) {
       const pathExists = await exists(filename);
       if (!pathExists) {
         console.error(chalk.red(`File or directory ${filename} does not exist`));
-        return;
+        process.exit(constants.EXIT_STATUS_ERROR_FILE_NOT_FOUND);
```
Comment (andreassiegel) [inline packages/bruno-cli/src/commands/run.js]:
```suggestion
        process.exit(constants.EXIT_STATUS.ERROR_FILE_NOT_FOUND);
```

File: packages/bruno-cli/src/commands/run.js [hunk 5]
```diff
@@ -282,7 +283,7 @@ const handler = async function (argv) {
 
       if (!envPathExists) {
         console.error(chalk.red(`Environment file not found: `) + chalk.dim(`environments/${env}.bru`));
-        return;
+        process.exit(constants.EXIT_STATUS_ERROR_ENV_NOT_FOUND);
```
Comment (andreassiegel) [inline packages/bruno-cli/src/commands/run.js]:
```suggestion
        process.exit(constants.EXIT_STATUS.ERROR_ENV_NOT_FOUND);
```

File: packages/bruno-cli/src/commands/run.js [hunk 6]
```diff
@@ -299,7 +300,7 @@ const handler = async function (argv) {
         processVars = envVar;
       } else {
         console.error(chalk.red(`overridable environment variables not parsable: use name=value`));
-        return;
+        process.exit(constants.EXIT_STATUS_ERROR_MALFORMED_ENV_OVERRIDE);
```
Comment (andreassiegel) [inline packages/bruno-cli/src/commands/run.js]:
```suggestion
        process.exit(constants.EXIT_STATUS.ERROR_MALFORMED_ENV_OVERRIDE);
```

File: packages/bruno-cli/src/commands/run.js [hunk 7]
```diff
@@ -310,7 +311,7 @@ const handler = async function (argv) {
               chalk.red(`Overridable environment variable not correct: use name=value - presented: `) +
                 chalk.dim(`${value}`)
             );
-            return;
+            process.exit(constants.EXIT_STATUS_ERROR_INCORRECT_ENV_OVERRIDE);
```
Comment (andreassiegel) [inline packages/bruno-cli/src/commands/run.js]:
```suggestion
            process.exit(constants.EXIT_STATUS.ERROR_INCORRECT_ENV_OVERRIDE);
```

File: packages/bruno-cli/src/commands/run.js [hunk 8]
```diff
@@ -339,7 +340,7 @@ const handler = async function (argv) {
 
     if (['json', 'junit', 'html'].indexOf(format) === -1) {
       console.error(chalk.red(`Format must be one of "json", "junit or "html"`));
-      return;
+      process.exit(constants.EXIT_STATUS_ERROR_INCORRECT_OUTPUT_FORMAT);
```
Comment (andreassiegel) [inline packages/bruno-cli/src/commands/run.js]:
```suggestion
      process.exit(constants.EXIT_STATUS.ERROR_INCORRECT_OUTPUT_FORMAT);
```

File: packages/bruno-cli/src/commands/run.js [hunk 9]
```diff
@@ -451,7 +452,7 @@ const handler = async function (argv) {
         nJumps++;
         if (nJumps > 10000) {
           console.error(chalk.red(`Too many jumps, possible infinite loop`));
-          process.exit(1);
+          process.exit(constants.EXIT_STATUS_ERROR_INFINTE_LOOP);
```
Comment (andreassiegel) [inline packages/bruno-cli/src/commands/run.js]:
```suggestion
          process.exit(constants.EXIT_STATUS.ERROR_INFINTE_LOOP);
```

Comment (andreassiegel) [inline packages/bruno-cli/src/commands/run.js]: I like the using a constant instead of a hardcoded result code! 🙂

File: packages/bruno-cli/src/commands/run.js [hunk 10]
```diff
@@ -477,7 +478,7 @@ const handler = async function (argv) {
       const outputDirExists = await exists(outputDir);
       if (!outputDirExists) {
         console.error(chalk.red(`Output directory ${outputDir} does not exist`));
-        process.exit(1);
+        process.exit(constants.EXIT_STATUS_ERROR_MISSING_OUTPUT_DIR);
```
Comment (andreassiegel) [inline packages/bruno-cli/src/commands/run.js]:
```suggestion
        process.exit(constants.EXIT_STATUS.ERROR_MISSING_OUTPUT_DIR);
```

File: packages/bruno-cli/src/commands/run.js [hunk 11]
```diff
@@ -497,12 +498,12 @@ const handler = async function (argv) {
     }
 
     if (summary.failedAssertions + summary.failedTests + summary.failedRequests > 0) {
-      process.exit(1);
+      process.exit(constants.EXIT_STATUS_ERROR_FAILED_COLLECTION);
```
Comment (andreassiegel) [inline packages/bruno-cli/src/commands/run.js]:
```suggestion
      process.exit(constants.EXIT_STATUS.ERROR_FAILED_COLLECTION);
```

File: packages/bruno-cli/src/commands/run.js [hunk 12]
```diff
@@ -497,12 +498,12 @@ const handler = async function (argv) {
...
     }
   } catch (err) {
     console.log('Something went wrong');
     console.error(chalk.red(err.message));
-    process.exit(1);
+    process.exit(constants.EXIT_STATUS_ERROR_GENERIC);
```
Comment (andreassiegel) [inline packages/bruno-cli/src/commands/run.js]:
```suggestion
    process.exit(constants.EXIT_STATUS.ERROR_GENERIC);
```

**Review by andreassiegel — COMMENTED** [review]
I second the idea of having more specific result codes or error codes. This has already helped a lot in CI/CD scripting with other tools, so I believe this is also helpful with Bruno CLI.

Please consider my suggestions for changes that might further improve the proposed changes.

**Review by andreassiegel — APPROVED** [review]
Looks good to me, I like this!

**Comment by jzorn** [comment]
@helloanoop Hey, did you have time to look at this change? Thanks! :)

**Comment by jzorn** [comment]
Anything? :)

**Comment by jzorn** [comment]
Friendly ping :)

**Comment by jzorn** [comment]
Is there anything I missed? Do I need to follow a different process to get a change merged?

**Comment by jzorn** [comment]
Anything @helloanoop ?

**Comment by helloanoop** [comment]
Merged. Thank you @jzorn !

Thank you @andreassiegel @lohxt1 for the review.
This will be shipped in today's release.
