### PR TITLE
fix: forward cookies from 4XX/5XX responses in collection runner and CLI

### LINKED ISSUE #7475: [Runner/CLI Only] Cookies are not forwarded if the response has a status 4XX
### I have checked the following:

- [x] I have searched existing issues and found nothing related to my issue.

### This bug is:

- [ ] making Bruno unusable for me
- [x] slowing me down but I'm able to continue working
- [ ] annoying
- [ ] this feature was working in a previous version but is broken in the current release.

### Bruno version

3.1.4

### Operating System

macOS 15.6.1

### Describe the bug

When a set-cookie header is set in a response with a status 413, the cookie is not forwarded to the next request

This problem appears only when I run from a runner or the CLI but not when I run each request manually.

The requests below are run on a server with 3 routes :
- GET /responds-200-with-a-cookie that sets  a cookie "MY_COOKIE" with the value "COOKIE_200" and responds with a status 200
- GET /responds-400-with-a-cookie that sets  a cookie "MY_COOKIE" with the value "COOKIE_400" and responds with a status 400
- GET /cookie that responds 200 with a body { cookie: `<the current value of the cookie MY_COOKIE>` }

### .bru file to reproduce the bug

meta {
  name: Response 200 and COOKIE 200
  type: http
  seq: 1
}

get {
  url: http://localhost:8080/responds-200-with-a-cookie
  body: none
  auth: inherit
}

settings {
  encodeUrl: true
}

---

meta {
  name: Check cookie is COOKIE_200
  type: http
  seq: 2
}

get {
  url: http://localhost:8080/cookie
  body: none
  auth: inherit
}

assert {
  res.body.cookie: eq COOKIE_200
}

settings {
  encodeUrl: true
  timeout: 0
}

---

meta {
  name: Response 400 and COOKIE 400
  type: http
  seq: 3
}

get {
  url: http://localhost:8080/responds-400-with-a-cookie
  body: none
  auth: inherit
}

assert {
  res.status: eq 400
}

settings {
  encodeUrl: true
  timeout: 0
}

---

meta {
  name: Check cookie is COOKIE_400
  type: http
  seq: 4
}

get {
  url: http://localhost:8080/responds-200-with-a-cookie
  body: none
  auth: inherit
}

assert {
  res.body.cookie: eq COOKIE_400
}

settings {
  encodeUrl: true
  timeout: 0
}

### Screenshots/Live demo link

Run manually: it works

Image

Run from a runner: it fails

Image

From the CLI: it fails also

Image

### PR DESCRIPTION
**Pull request by abhishek-bruno**
### Description

[JIRA](https://usebruno.atlassian.net/browse/BRU-2871)

## Problem

When a server responds with a 4XX/5XX status and includes a `Set-Cookie` header,
the cookie was silently dropped when running from the **collection runner** or **CLI**.
Running each request manually worked correctly.

Fixes #7475

## Root Cause

Axios throws an error for non-2XX responses, jumping execution to the `catch` block.
`saveCookies()` was only called in the `try` block (the 2XX path), so error-status
cookies were never persisted to the cookie jar.

The manual single-request path in the Electron app was already correct —
`saveCookies()` is called *after* the try/catch there, so both paths were covered.

## Fix

Added `saveCookies()` to the `catch` block in both affected runner code paths:

| File | Location |
|---|---|
| `packages/bruno-cli/src/runner/run-single-request.js` | CLI runner |
| `packages/bruno-electron/src/ipc/network/index.js` | App collection runner |

## Testing

Start the local test server and create a 2-request collection:

1. `GET /responds-4xx-with-cookie` — returns 400 with `Set-Cookie: MY_COOKIE=COOKIE_400`
2. `GET /cookie` — echoes back the `Cookie` header

Run both via the **collection runner**. After this fix, request 2 receives
`MY_COOKIE=COOKIE_400`. Before the fix, the cookie field is empty.

#### Contribution Checklist:

- [ ] **I've used AI significantly to create this pull request**
- [ ] **The pull request only addresses one issue or adds one feature.**
- [ ] **The pull request does not introduce any breaking changes**
- [ ] **I have added screenshots or gifs to help explain the change if applicable.**
- [ ] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [ ] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

#### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

## Summary by CodeRabbit

* **Bug Fixes**
  * Cookies from error responses (4XX/5XX errors) are now properly persisted, ensuring consistent cookie handling across all HTTP responses.

### CODE REVIEW

**Comment by ahamayeah59** [comment]
So it's exactlly the same issue mentionned 6 months ago  in https://github.com/usebruno/bruno/issues/5658  with 3xx redirect response but with 4xx and 5xx reponse.... A shame that it takes so long to fix this !

File: packages/bruno-electron/src/ipc/network/index.js [hunk 1]
```diff
@@ -1630,6 +1630,11 @@ const registerNetworkIpc = (mainWindow) => {
                 error.response.data = data;
                 error.response.dataBuffer = dataBuffer;
 
+                // save cookies (4XX/5XX responses can also set cookies)
+                if (preferencesUtil.shouldStoreCookies()) {
```
Comment (sanish-bruno) [inline packages/bruno-electron/src/ipc/network/index.js:1634]: @abhishek-bruno is it possible to have some test cases?
