### PR TITLE
fix: support multiline descriptions in example blocks

### LINKED ISSUE #6861: Multiline comment breaks the example
### I have checked the following:

- [x] I have searched existing issues and found nothing related to my issue.

### This bug is:

- [ ] making Bruno unusable for me
- [ ] slowing me down but I'm able to continue working
- [ ] annoying
- [ ] this feature was working in a previous version but is broken in the current release.

### Bruno version

3.0.2

### Operating System

Windows 11

### Describe the bug

When adding a multiline comment to an example, only an icon appears in the menu without the title. After clicking in the menu, data is not loaded. And when trying to rename it, it aborts.

```
Stack Trace
Cannot read properties of undefined (reading 'trim')

TypeError: Cannot read properties of undefined (reading 'trim')
    at Td (file:///.../.../Bruno/resources/app.asar/web/static/js/index.d69da622.js:864:252265)
    at lb (file:///.../.../Bruno/resources/app.asar/web/static/js/lib-react.41929aa2.js:2:41685)
    at aY (file:///.../.../Bruno/resources/app.asar/web/static/js/lib-react.41929aa2.js:2:61437)
    at ot (file:///.../.../Bruno/resources/app.asar/web/static/js/lib-react.41929aa2.js:2:72858)
    at ua (file:///.../.../Bruno/resources/app.asar/web/static/js/lib-react.41929aa2.js:2:111999)
    at file:///.../.../Bruno/resources/app.asar/web/static/js/lib-react.41929aa2.js:2:111844
    at ul (file:///.../.../Bruno/resources/app.asar/web/static/js/lib-react.41929aa2.js:2:111852)
    at i3 (file:///.../.../Bruno/resources/app.asar/web/static/js/lib-react.41929aa2.js:2:109022)
    at uL (file:///.../.../Bruno/resources/app.asar/web/static/js/lib-react.41929aa2.js:2:129001)
    at uP (file:///.../.../Bruno/resources/app.asar/web/static/js/lib-react.41929aa2.js:2:127408)
```

### .bru file to reproduce the bug

```
example {
  name: Test
  description: Test1
  Test2
  
  request: {
```

### Screenshots/Live demo link

Image

Image

### PR DESCRIPTION
**Pull request by gopu-bruno**
### Description

Fixes the crash when multiline descriptions are used in example blocks.

Fixes #6861

### Problem 

When adding a multiline description to an example block, the parser would fail, causing:
- `TypeError: Cannot read properties of undefined (reading 'trim')`
- Examples appearing without names in the UI
- Inability to rename or interact with affected example

### Root Cause

The example grammar only supported single-line values for `description`. When multiline descriptions was added the parser would fail, producing example objects with `undefined` properties.

### Changes
- Updated grammar to support multiline descriptions using `'''` delimiters
- Implemented multiline text block parsing with indentation handling

#### Contribution Checklist:

- [ ] **I've used AI significantly to create this pull request**
- [x] **The pull request only addresses one issue or adds one feature.**
- [x] **The pull request does not introduce any breaking changes**
- [ ] **I have added screenshots or gifs to help explain the change if applicable.**
- [x] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [ ] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

#### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

## Summary by CodeRabbit

* **Bug Fixes**
  * Prevented empty or whitespace-only example rename entries by initializing edit values and tightening validation.

* **New Features**
  * Added robust support for multiline example descriptions, preserving indentation and optional content type during parsing and serialization.
  * Descriptions are now normalized (trimmed) and handled correctly when missing.

* **Tests**
  * Added tests and fixtures to verify multiline description parsing and round-trip behavior.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: packages/bruno-lang/v2/src/example/bruToJson.js [hunk 1]
```diff
@@ -85,9 +88,23 @@ const astExampleAttribute = {
...
   description(_1, _2, _3, _4, value, _6) {
     return {
-      description: value.sourceString ? value.sourceString.trim() : ''
+      description: value.ast ? value.ast.trim() : ''
     };
   },
+  descriptionvalue(content) {
+    return content.ast;
+  },
+  multilinetextblock(_1, content, _2, _3, contentType) {
```
Comment (sanish-bruno) [inline packages/bruno-lang/v2/src/example/bruToJson.js:96]: @gopu-bruno  multiline text block should be part of `astBaseAttribute` i guess, may be we already have it there!

Comment (sanish-bruno) [reply packages/bruno-lang/v2/src/example/bruToJson.js:96]: the grammar within attributes seems to be using 4 level of indent, here it seems like we are only outdenting 2 spaces, nevertheless, we can use `outdentString`  function i guess @gopu-bruno

File: packages/bruno-lang/v2/src/example/jsonToBru.js [hunk 2]
```diff
@@ -38,7 +38,8 @@ const jsonToExampleBru = (json) => {
   }
 
   if (description) {
-    bru += `description: ${description}\n`;
+    const descriptionValue = getValueString(description);
```
Comment (sanish-bruno) [inline packages/bruno-lang/v2/src/example/jsonToBru.js:41]: @gopu-bruno test the behaviour when the description is undefined/not provided,  can add a test cases for this condition too

File: packages/bruno-lang/v2/src/example/bruToJson.js (hunk 1 above)
Comment (gopu-bruno) [reply packages/bruno-lang/v2/src/example/bruToJson.js:96]: @sanish-bruno, true we already have a `multilinetextblock` as part of `astBaseAttribute` and it uses `slice(4)`. However, the example content here is already pre-processed by `parseExampleContent()` which remove the top level 2 spaces.

File: packages/bruno-lang/v2/src/example/jsonToBru.js (hunk 2 above)
Comment (gopu-bruno) [reply packages/bruno-lang/v2/src/example/jsonToBru.js:41]: Test cases has been added for the same.

File: packages/bruno-lang/v2/tests/examples/examples.spec.js [hunk 3]
```diff
@@ -309,6 +354,40 @@ example {
     });
   });
 
+  describe('Examples with multiline descriptions', () => {
+    it('should parse examples with multiline descriptions', () => {
+      const input = fs.readFileSync(path.join(__dirname, 'fixtures', 'bru', 'examples-multiline-description.bru'), 'utf8');
+      const expected = require('./fixtures/json/examples-multiline-description.json');
+      const output = bruToJson(input);
```
Comment (sanish-bruno) [inline packages/bruno-lang/v2/tests/examples/examples.spec.js:361]: I think we may need to add a test case that will do that jsonToBru converions with the  same files
