### PR TITLE
fix: add uuid v7 support in pre-request scripts

### LINKED ISSUE #7333: Using Inbuilt Libraries in Pre request script not working
### I have checked the following:

- [x] I have searched existing issues and found nothing related to my issue.

### This bug is:

- [x] making Bruno unusable for me
- [x] slowing me down but I'm able to continue working
- [x] annoying
- [x] this feature was working in a previous version but is broken in the current release.

### Bruno version

3.1.2

### Operating System

Windows 11, Linux

### Describe the bug

Im using the following script in my pre request script

const { v7: uuidv7 } = require('uuid');

const logUUID = uuidv7();
const commandUUID = uuidv7();

console.log("Generated logID:", logUUID);
console.log("Generated commandID:", commandUUID);

bru.setVar("logID", logUUID);
bru.setVar("commandID", commandUUID);

When i run the request i get the error uuidv7 is not a function

Im using the dev mode

### .bru file to reproduce the bug

[create-objs.yml](https://github.com/user-attachments/files/25614968/create-objs.yml)

### Screenshots/Live demo link

Image

### PR DESCRIPTION
**Pull request by chirag-bruno**
### Description

[JIRA](https://usebruno.atlassian.net/browse/BRU-2816)

Fixes #7333 - uuid v7 was not working in pre-request scripts because the uuid dependency was pinned to ^9.0.0, but v7/v6 functions were only added in uuid v10.0.0.

Changes:
- Upgrade uuid dependency from ^9.0.0 to ^10.0.0 in bruno-js and bruno-electron packages
- Extract require() module loader into reusable shims/require.js
- Add comprehensive tests for uuid shim (v1-v7, utilities, conversions)
- Add tests for require shim functionality
- Add createEvalHelper test utility to quickjs utils

[JIRA](https://usebruno.atlassian.net/browse/BRU-2816)

#### Contribution Checklist:

- [ ] **I've used AI significantly to create this pull request**
- [ ] **The pull request only addresses one issue or adds one feature.**
- [ ] **The pull request does not introduce any breaking changes**
- [ ] **I have added screenshots or gifs to help explain the change if applicable.**
- [ ] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [ ] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

#### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

## Summary by CodeRabbit

* **Chores**
  * Updated uuid dependency from v9 to v10 across packages

* **New Features**
  * Improved sandbox module loader with a shared require shim for better local-module resolution
  * Added sandbox test helper utilities for evaluating code in VM contexts

* **Tests**
  * Added comprehensive tests for the sandbox module system and UUID functionality (v1/v3/v4/v5/v6/v7, utilities, parsing/validation)

### CODE REVIEW

File: packages/bruno-js/src/sandbox/quickjs/shims/require.js [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+ * Returns JavaScript code that sets up the require() function in the QuickJS VM.
+ * This module loader looks up modules from globalThis.requireObject and optionally
+ * supports loading local modules if the necessary context (bru.cwd, __brunoLoadLocalModule) is available.
+ *
+ * @param {Object} options
+ * @param {boolean} options.enableLocalModules - Whether to enable local module loading (requires bru context)
+ * @returns {string} JavaScript code to eval in the VM
+ */
+function getRequireCode({ enableLocalModules = true } = {}) {
+  if (!enableLocalModules) {
```
Comment (bijin-bruno) [inline packages/bruno-js/src/sandbox/quickjs/shims/require.js]: is this being used anywhere except tests? @chirag-bruno

File: packages/bruno-js/src/sandbox/quickjs/utils/index.js [hunk 2]
```diff
@@ -77,7 +77,36 @@ async function invokeFunction(vm, quickFn, args = []) {
...
 
+/**
+ * Evaluates code in a QuickJS VM and returns the dumped result.
+ * Handles unwrapping and disposing of handles automatically.
+ *
+ * @param {Object} vm - QuickJS VM context
+ * @param {string} code - JavaScript code to evaluate
+ * @returns {*} The evaluated and dumped result
+ */
+function evalAndDump(vm, code) {
```
Comment (sanish-bruno) [inline packages/bruno-js/src/sandbox/quickjs/utils/index.js]: **Suggestion**: `evalAndDump` and `createEvalHelper` are test-only utilities being added to a production module (`utils/index.js`). Consider placing them in a dedicated test helper file (e.g., `utils/test-helpers.js` or `__tests__/helpers.js`) to keep the production code surface minimal.

This is non-blocking — the functions are harmless in production, but separating test infrastructure from runtime code is generally a good practice.

File: packages/bruno-js/src/sandbox/quickjs/shims/lib/uuid.spec.js [hunk 3]
```diff
@@ -0,0 +1,163 @@
...
+
+    it.each([
+      { fn: 'v3', version: 3 },
+      { fn: 'v5', version: 5 }
+    ])('$fn should generate valid uuid with namespace', ({ fn, version }) => {
+      const uuid = evalAndDump(`
+        const { ${fn} } = require('uuid');
+        ${fn}('example.com', '${DNS_NAMESPACE}');
+      `);
+      expect(uuid).toMatch(uuidPattern(version));
```
Comment (sanish-bruno) [inline packages/bruno-js/src/sandbox/quickjs/shims/lib/uuid.spec.js]: **Nit**: The string comparison `uuid1 <= uuid2` works for UUIDv7 ordering because the timestamp is encoded in the most significant bits and uuid v10 uses a monotonic counter within the same millisecond. Just noting this is correct but non-obvious — a brief comment like `// v7 UUIDs are lexicographically sortable by design` would help future readers understand why string comparison is valid here.

**Review by sanish-bruno — COMMENTED** [review]
## PR Review

Found **2** issue(s): 0 major, 0 minor, 1 suggestion, 1 nit.

### Summary
- The core fix is correct: upgrading uuid from ^9 to ^10 enables v6/v7 support that was already wired in the shim but non-functional
- The require shim extraction is clean — the `enableLocalModules: true` code path is identical to the original inline code
- Tests are comprehensive and cover the exact regression scenario from #7333

File: packages/bruno-js/src/sandbox/quickjs/shims/lib/uuid.spec.js [hunk 4]
```diff
@@ -0,0 +1,164 @@
...
+      }
+      module = null;
+    }
+  });
+
+  /**
+   * Regex pattern for validating UUID format with specific version
+   */
+  function uuidPattern(version) {
+    return new RegExp(`^[0-9a-f]{8}-[0-9a-f]{4}-${version}[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`, 'i');
```
Comment (sid-bruno) [inline packages/bruno-js/src/sandbox/quickjs/shims/lib/uuid.spec.js]: The regex for the random and time might not always match with all the specs, might need checking
