### PR TITLE
fix(cli): preserve request item type during import and fail on unsupported types

### LINKED ISSUE #7172: Error stringifying item: Error: Unsupported item type: http
### I have checked the following:

- [x] I have searched existing issues and found nothing related to my issue.

### This bug is:

- [ ] making Bruno unusable for me
- [ ] slowing me down but I'm able to continue working
- [ ] annoying
- [x] this feature was working in a previous version but is broken in the current release.

### Bruno version

3.1.0

### Operating System

MacOS

### Describe the bug

The latest version of `@usebruno/cli` is not working properly.

The `import` command responds with this error:
```bash
 Error stringifying item: Error: Unsupported item type: http
```

### .bru file to reproduce the bug

_No response_

### Screenshots/Live demo link

Steps to reproduce the bug:

1) Download the `petstore.yaml` file from here:
https://raw.githubusercontent.com/swagger-api/swagger-codegen/refs/heads/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml

2) Run the latest version of `@usebruno/cli`
```bash
npx @usebruno/cli import openapi --source petstore.yaml --output temp  --collection-name "pet-store-api"
````

3) Check the error:
Image

### PR DESCRIPTION
**Pull request by rameshsunkara**
## Summary
Fix CLI import serialization in `createCollectionFromBrunoObject` so generated `.bru` files are valid and compatible with filestore expectations.

Fixes #7172.

## Problem
`bru import openapi` could fail with:

`Unsupported item type: http`

Root cause:
- CLI converted request item types from schema values (`http-request`, `graphql-request`) to legacy values (`http`, `graphql`) before calling `stringifyRequest`.
- Request/folder serialization relied on filestore defaults instead of explicitly writing BRU format.

## Changes
- Preserve schema request types when building request objects for stringify:
  - `http-request` stays `http-request`
  - `graphql-request` stays `graphql-request`
- Explicitly serialize imported request and folder files using BRU format:
  - `stringifyRequest(..., { format: 'bru' })`
  - `stringifyFolder(..., { format: 'bru' })`
- Add fail-fast handling for unsupported item types in import writer path.
- Add focused regression tests:
  - writes/reads HTTP and GraphQL `.bru` requests correctly
  - writes/reads `folder.bru` correctly
  - throws on unsupported item type

## Files
- `packages/bruno-cli/src/utils/collection.js`
- `packages/bruno-cli/tests/utils/collection/create-collection-from-bruno-object.spec.js`

## Validation
Target test added:
`packages/bruno-cli/tests/utils/collection/create-collection-from-bruno-object.spec.js`

Recommended command:
`npm run test --workspace=packages/bruno-cli -- tests/utils/collection/create-collection-from-bruno-object.spec.js`

## Summary by CodeRabbit

* **Refactor**
  * Apply BRU formatting explicitly during collection export and preserve original request types in exported BRU files.

* **Tests**
  * Added tests that verify exported BRU files are written for HTTP and GraphQL requests and for folders, and that parsed files retain correct types, methods, and metadata.

### CODE REVIEW

File: packages/bruno-cli/src/utils/collection.js [hunk 1]
```diff
@@ -499,7 +499,7 @@ const processCollectionItems = async (items = [], currentPath) => {
         if (item.seq) {
           item.root.meta.seq = item.seq;
         }
-        const folderContent = await stringifyFolder(item.root);
+        const folderContent = await stringifyFolder(item.root, { format: 'bru' });
```
Comment (rameshsunkara) [inline packages/bruno-cli/src/utils/collection.js]: @sanjaikumar-bruno 

Thanks for the quick review and good callout. ~~I removed the unrelated changes and kept this one intentionally.~~

`collection.js` supports reading both `yml` and `bru`, but this import path (`createCollectionFromBrunoObject`) only writes Bruno files (`bruno.json`, `collection.bru`, `folder.bru`, `*.bru`).

Since filestore’s default stringify format is `yml`, passing `{ format: 'bru' }` here prevents writing yml-formatted content into `.bru` files.

Comment (rameshsunkara) [reply packages/bruno-cli/src/utils/collection.js]: I kept the changes as coderabbit correctly called out about not having error handling for unsupported type.

And for this change, 
1. await is not needed at all, it just returns string
2. format bru is needed as explained above

**Comment by rameshsunkara** [comment]
@sanjaikumar-bruno sorry I didn't see you approved it and pushed a change based on coderabbit comments.

I think these are good changes, if you dont agree please let me know, I will revert. Please look at my comment above

**Comment by bijin-bruno** [comment]
Hey @rameshsunkara,

Thanks for your contribution! We’re merging this PR.

There’s also an ongoing internal effort to add support for the YML format: https://github.com/usebruno/bruno/pull/7028
cc - @pooja-bruno @sid-bruno
