### PR TITLE
fix: isJson assertion should accept arrays as valid JSON

### LINKED ISSUE #7556: Assert Section Signals Invalid JSON For Array With String Values
### I have checked the following:

- [x] I have searched existing issues and found nothing related to my issue.

### This bug is:

- [ ] making Bruno unusable for me
- [ ] slowing me down but I'm able to continue working
- [x] annoying
- [x] this feature was working in a previous version but is broken in the current release.

### Bruno version

3.1.4

### Operating System

macOS Tahoe 26.3.1 (a)

### Describe the bug

I usually have some basic assertions for all requests. I noticed that Bruno is failing a simple `res.body` `isJson` assertion now for some responses that are just a collection of string values; for instance:

```javascript
[
  "A55001213ZX0A"
]
```

### .bru file to reproduce the bug

```bru
meta {
  name: Some Identifier
  type: http
}

get {
  url: {{api-host}}/resource/{{resource-id}}
  body: none
}

headers {
  Accept: application/json
}

vars:pre-request {
  resource-id: A55001213ZX0A
}

assert {
  res.status: eq 200
  res.body: isJson
}
```

### Screenshots/Live demo link

N/A

### PR DESCRIPTION
**Pull request by abhishek-bruno**
### Description

[JIRA](https://usebruno.atlassian.net/browse/BRU-2993)

- Fixes the `isJson` assertion to accept JSON arrays (e.g. `["A55001213ZX0A"]`), which were incorrectly rejected
- Updates existing test and adds new test cases for array variants

## Context
The `isJson` chai property explicitly excluded arrays with `!Array.isArray(obj)`. This caused `res.body: isJson` assertions to fail for API responses returning JSON arrays — a valid and common response format.

Fixes #7556

## Test plan
- [x] Existing `isJson` tests updated and passing
- [x] New tests for: array of strings, empty array, array of objects
- [x] Plain object assertions still pass
- [x] Cross-realm object assertions still pass
- [x] String and null still correctly fail

#### Contribution Checklist:

- [ ] **I've used AI significantly to create this pull request**
- [ ] **The pull request only addresses one issue or adds one feature.**
- [ ] **The pull request does not introduce any breaking changes**
- [ ] **I have added screenshots or gifs to help explain the change if applicable.**
- [ ] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [ ] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

#### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

## Summary by CodeRabbit

* **Bug Fixes**
  * The `isJson` assertion now treats arrays (including empty arrays, arrays of primitives, and arrays of objects) as valid JSON; previously it accepted only plain objects. Assertion behavior and error reporting remain unchanged.

* **Tests**
  * Test suite updated to mark array cases as passing JSON assertions while retaining failing cases for non-array negatives (e.g., strings, null).

### CODE REVIEW

File: packages/bruno-js/src/runtime/assert-runtime.js [hunk 1]
```diff
@@ -17,8 +17,8 @@ chai.use(function (chai, utils) {
     // Objects created inside Node's vm.createContext() have a different Object constructor,
     // so obj.constructor === Object fails for objects passed via res.setBody() from scripts.
     // Note: toString check is more permissive than constructor check — custom class instances
-    const isJson = typeof obj === 'object' && obj !== null && !Array.isArray(obj)
-      && Object.prototype.toString.call(obj) === '[object Object]';
+    const isJson = typeof obj === 'object' && obj !== null
+      && (Array.isArray(obj) || Object.prototype.toString.call(obj) === '[object Object]');
```
Comment (bijin-bruno) [inline packages/bruno-js/src/runtime/assert-runtime.js:21]: Please make the same changes for `packages/bruno-js/src/sandbox/quickjs/shims/test.js`
