### PR TITLE
bugfix(#2462)

### LINKED ISSUE #2462: [Postman] Importing request with "formdata" of type "file" fails silently
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

`index.html:1 Uncaught (in promise) Error: Error invoking remote method 'renderer:import-collection': TypeError: Cannot read properties of undefined (reading 'includes')`

As per https://schema.postman.com/collection/json/v2.1.0/draft-07/collection.json:683, a formdata body may have "key:value" attributes for type "string", but "key:src" instead for type "file".

### .bru file to reproduce the bug
````
{
	"info": {
		"_postman_id": "redacted",
		"name": "redacted",
		"description": "redacted",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
		"_exporter_id": "",
		"_collection_link": ""
	},
	"item": [
		{
			"name": "Profile",
			"item": [
				{
					"name": "Update profile avatar",
					"request": {
						"auth": {
							"type": "bearer",
							"bearer": [
								{
									"key": "token",
									"value": "{{AUTH_TOKEN}}",
									"type": "string"
								}
							]
						},
						"method": "POST",
						"header": [
							{
								"key": "Accept",
								"value": "application/json",
								"type": "text"
							},
							{
								"key": "Content-Type",
								"value": "application/json",
								"type": "text"
							}
						],
						"body": {
							"mode": "formdata",
							"formdata": [
								{
									"key": "avatar",
									"type": "file",
									"src": "/Users/darylteo/Downloads/demo-images/001.jpg"
								}
							]
						},
						"url": {
							"raw": "{{API_URL}}/auth/profile/avatar",
							"host": [
								"{{API_URL}}"
							],
							"path": [
								"auth",
								"profile",
								"avatar"
							]
						},
						"description": ""
					},
					"response": [
						
					]
				}
			]
		}
	]
}
````

### Screenshots/Live demo link

https://imgur.com/XmfbmLO

### PR DESCRIPTION
**Pull request by sanjai0py**
# Description

fixes #2462

### Contribution Checklist:

- [ ] **The pull request only addresses one issue or adds one feature.**
- [ ] **The pull request does not introduce any breaking changes**
- [ ] **I have added screenshots or gifs to help explain the change if applicable.**
- [ ] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [ ] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

### CODE REVIEW

File: packages/bruno-app/src/utils/importers/postman-collection.js [hunk 1]
```diff
@@ -181,11 +181,22 @@ const importPostmanV2CollectionItem = (brunoParent, item, parentAuth, options) =
           if (bodyMode === 'formdata') {
             brunoRequestItem.request.body.mode = 'multipartForm';
             each(i.request.body.formdata, (param) => {
+              const isFile = param.type === 'file';
+              let value;
+              if (isFile) {
+                if (Array.isArray(param.src)) {
```
Comment (jwetzell) [inline packages/bruno-app/src/utils/importers/postman-collection.js]: Why the if/else if both paths have the same inside logic `value = param.src`?

**Comment by helloanoop** [comment]
Merged.

Thanks for taking care of this @sanjai0py !
