### PR TITLE
fix: qol fixes for keybindings

### LINKED ISSUE #7347: The cmd + h ignored when the output window is in focus
### I have checked the following:

- [x] I have searched existing issues and found nothing related to my issue.

### This bug is:

- [ ] making Bruno unusable for me
- [x] slowing me down but I'm able to continue working
- [x] annoying
- [ ] this feature was working in a previous version but is broken in the current release.

### Bruno version

3.1.4

### Operating System

macOS Tahoe 26.3 (25D125)

### Describe the bug

While the output section is focused (the one where the response is rendered), the `⌘ + h` to hide the app is intercepted and ignored. For the `⌘ + h` to work, I need to click outside of this window, and then the keyboard shortcut works as expected.

I'm not sure if related, but there are a few other issues that report misfunctioning key mappings:

- https://github.com/usebruno/bruno/issues/4109
- https://github.com/usebruno/bruno/issues/4108

### .bru file to reproduce the bug

No specific config is needed for the to reproduce. It is a global issue.

### Screenshots/Live demo link

https://github.com/user-attachments/assets/6dff564d-5b57-4438-b2f9-59192d5a9a6a

### PR DESCRIPTION
**Pull request by shubh-bruno**
### Description

[JIRA](https://usebruno.atlassian.net/browse/BRU-3048)

Also fixes : #7347

- Correction to the default maps for windows 
- Fix the Enter keyboard shortcut on the new request modal
- Fix .env file table save shortcut 

#### Contribution Checklist:

- [ ] **I've used AI significantly to create this pull request**
- [ ] **The pull request only addresses one issue or adds one feature.**
- [ ] **The pull request does not introduce any breaking changes**
- [ ] **I have added screenshots or gifs to help explain the change if applicable.**
- [ ] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [ ] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

#### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

## Summary by CodeRabbit

* **Bug Fixes**
  * Disable replace shortcut in read‑only editors; editor inputs now capture global shortcuts reliably.
  * Windows reserved shortcuts list adjusted to reduce conflicts.
  * Env saves prefixed with "dotenv:" follow the specialized save flow.
  * Transient tabs are no longer recorded for reopening.

* **New Features**
  * Request URL field can run/submit directly from the editor.

* **Style**
  * Keybindings UI spacing, keycap sizing, and row styles updated; reset button disabled when no custom bindings and shows success toast.

### CODE REVIEW

**Review by sid-bruno — DISMISSED** [review]

File: packages/bruno-app/src/components/Preferences/Keybindings/index.js [hunk 1]
```diff
@@ -218,23 +218,21 @@ const RESERVED_BY_OS = {
...
   windows: new Set([
+    // System-level shortcuts (intercepted by Windows before reaching the app)
     comboSignature(['alt', 'tab']),
+    comboSignature(['alt', 'shift', 'tab']),
     comboSignature(['alt', 'f4']),
-    comboSignature(['f1']), // Windows Help
+    comboSignature(['alt', 'esc']),
+    comboSignature(['alt', 'space']),
     comboSignature(['ctrl', 'alt', 'delete']),
-    comboSignature(['command', 'l']),
```
Comment (sanish-bruno) [inline packages/bruno-app/src/components/Preferences/Keybindings/index.js:225]: @shubh-bruno is there any reason why we removed these keybindings, `cmd + ` ones?

**Review by sanish-bruno — CHANGES_REQUESTED** [review]

File: packages/bruno-app/src/components/Preferences/Keybindings/index.js (hunk 1 above)
Comment (sid-bruno) [reply packages/bruno-app/src/components/Preferences/Keybindings/index.js:225]: Windows keybinds, don't have `command`

**Review by sanish-bruno — APPROVED** [review]

**Review by bijin-bruno — DISMISSED** [review]

**Comment by helloanoop** [comment]
@shubh-bruno Is there anyway we could add a playwright test to ensure that issue #7347 (cmd + h ignored when the output window is in focus) does not regress ever again ?

**Comment by shubh-bruno** [comment]
@helloanoop i can't think of anything right now as it gets intercepted at OS level, window gets hidden so Playwright assertions are possible out of electron

File: packages/bruno-app/src/components/Preferences/Keybindings/StyledWrapper.js [hunk 2]
```diff
@@ -220,23 +238,25 @@ const StyledWrapper = styled.div`
...
+    font-size: 10px;
     font-weight: 500;
     line-height: 1;
   }
 
-  tbody tr.row-success td {
-    background: #2E8A540F;
+  tbody tr.row-success td,
+  tbody tr.row-success:hover td {
+    background: #2E8A540F !important;
```
Comment (sid-bruno) [inline packages/bruno-app/src/components/Preferences/Keybindings/StyledWrapper.js]: use colors from `theme.status` instead

File: packages/bruno-app/src/components/Preferences/Keybindings/StyledWrapper.js [hunk 3]
```diff
@@ -220,23 +238,25 @@ const StyledWrapper = styled.div`
...
   }
 
-  tbody tr.row-error td {
-    background: #D32F2F0F;
+  tbody tr.row-error td,
+  tbody tr.row-error:hover td {
+    background: #D32F2F0F !important;
```
Comment (sid-bruno) [inline packages/bruno-app/src/components/Preferences/Keybindings/StyledWrapper.js]: use colors from `theme.status` instead

File: packages/bruno-app/src/components/Preferences/Keybindings/StyledWrapper.js
Comment (sid-bruno) [inline packages/bruno-app/src/components/Preferences/Keybindings/StyledWrapper.js]: use colors from `theme.status` instead

**Review by sid-bruno — DISMISSED** [review]

**Review by sid-bruno — APPROVED** [review]

**Review by lohit-bruno — APPROVED** [review]
