### PR TITLE
fix: add size and duration fields to CLI bru.runRequest() response

### LINKED ISSUE #7352: Result object of `bru.runRequest()` is inconsistent between GUI and CLI
### I have checked the following:

- [x] I have searched existing issues and found nothing related to my issue.

### This bug is:

- [ ] making Bruno unusable for me
- [x] slowing me down but I'm able to continue working
- [x] annoying
- [ ] this feature was working in a previous version but is broken in the current release.

### Bruno version

3.1.4

### Operating System

Windows 11

### Describe the bug

A collection with the following script:

```js
const result = await bru.runRequest('Run a query.bru')
console.log('properties of result object: ' + Object.getOwnPropertyNames(result).join(', '))
```

When run from the GUI logs:

```
properties of result object: status, statusText, headers, data, stream, cancelTokenUid, dataBuffer, size, duration, url, timeline
```

When run from the CLI logs:

```
properties of result object: status, statusText, headers, data, url, responseTime
```

Notably, `size` is missing from the CLI run, and `duration` has changed to `responseTime`. I also can't find any documentation on what the result object *should* look like.

It's possible to approximate size by doing something like `JSON.stringify(result.data).length`, but it won't produce the same numbers as `result.size`.

### .bru file to reproduce the bug

_No response_

### Screenshots/Live demo link

Image

### PR DESCRIPTION
**Pull request by chirag-bruno**
### Description

Add `size` and `duration` fields to the response object in CLI to match GUI behavior, ensuring consistent API for bru.runRequest() across both environments.

- `duration` is an alias for `responseTime` for GUI compatibility
- `size` is the byte length of the response buffer (0 for errors/skipped)

Fixes #7352
[JIRA](https://usebruno.atlassian.net/browse/BRU-2832)

#### Contribution Checklist:

- [ ] **I've used AI significantly to create this pull request**
- [ ] **The pull request only addresses one issue or adds one feature.**
- [ ] **The pull request does not introduce any breaking changes**
- [ ] **I have added screenshots or gifs to help explain the change if applicable.**
- [ ] **I have read the [contribution guidelines](https://github.com/usebruno/bruno/blob/main/contributing.md).**
- [ ] **Create an issue and link to the pull request.**

Note: Keeping the PR small and focused helps make it easier to review and merge. If you have multiple changes you want to make, please consider submitting them as separate pull requests.

#### Publishing to New Package Managers

Please see [here](../publishing.md) for more information.

## Summary by CodeRabbit

* **New Features**
  * Request results now include duration and size metrics alongside response time for improved performance insight.

* **Bug Fixes**
  * Metrics reliably default to 0 for skipped or failed requests; response time is normalized from headers when available and used to populate duration.

* **Tests**
  * Added tests validating duration, size, and responseTime behavior for skipped, successful, and error scenarios.

### CODE REVIEW

File: packages/bruno-cli/src/runner/run-single-request.js [hunk 1]
```diff
@@ -957,7 +965,9 @@ const runSingleRequest = async function (
         headers: response.headers,
         data: response.data,
         url: response.request ? response.request.protocol + '//' + response.request.host + response.request.path : null,
-        responseTime
+        responseTime,
+        duration: responseTime,
```
Comment (sanish-bruno) [inline packages/bruno-cli/src/runner/run-single-request.js:916]: **Suggestion**: In the GUI (`bruno-electron/src/ipc/network/index.js`), `duration` and `responseTime` are actually different values:

- `duration` = `timeEnd - timeStart` (wall-clock elapsed time measured around the axios call)
- `responseTime` = from the custom `request-duration` header injected by the axios interceptor

Setting `duration: responseTime` here makes them identical in the CLI, which is a reasonable approximation since the CLI doesn't have the same `timeStart`/`timeEnd` timing wrapper. But it might be worth adding a brief comment so future readers understand this is intentional:

```js
// In the GUI, duration is wall-clock time (timeEnd - timeStart).
// In the CLI we use responseTime as a close approximation.
duration: responseTime,
```

This also means scripts using `bru.runRequest()` will see identical `duration` and `responseTime` values in the CLI but potentially different values in the GUI. Probably fine for most use cases, but worth documenting.

**Comment by sanish-bruno** [comment]
@chirag-bruno can we have test cases to verify this?

File: packages/bruno-cli/tests/runner/response-fields.spec.js [hunk 2]
```diff
@@ -0,0 +1,193 @@
...
+    // Use a plain object with get/delete to simulate axios headers
+    const headers = {
+      get: (key) => key === 'request-duration' ? '253' : null,
+      delete: jest.fn()
+    };
+
+    prepareRequest.mockResolvedValue({
+      method: 'GET',
+      url: 'http://example.com/api',
+      headers: {},
```
Comment (sanish-bruno) [inline packages/bruno-cli/tests/runner/response-fields.spec.js:150]: **Nit**: Dead code — `mockHeaders` Map is created but never used (the plain `headers` object on line 153 is what gets passed to the mock response).

Also, the `delete` override on line 150 would cause infinite recursion if called (`this.delete(key)` calls itself since `this.delete` was just replaced).

Suggested fix: remove lines 149-150.
```js
// Remove these two lines:
const mockHeaders = new Map([['request-duration', '253']]);
mockHeaders.delete = function (key) { this.delete(key); };
```
